version: "3.1"
services:
  java-serice:
    build: .
    container_name: "java-app"
    depends_on:
      - postgresqldb
    ports:
      - 8080:8080
  postgresqldb:
    image: postgres:latest
    restart: always
    container_name: postgresqldb
    ports:
      - 5432:5432
    environment:
       POSTGRES_USER: postgres
       POSTGRES_PASSWORD: postgres
       POSTGRES_DB: test